### List locations
GET http://localhost:8080/api/locations
Accept: application/json

### Get location with id 1
GET http://localhost:8080/api/locations/1
Accept: application/json

### Get location with invalid id
GET http://localhost:8080/api/locations/666
Accept: application/json

### Create a location
POST http://localhost:8080/api/locations
Accept: application/json
Content-Type: application/json

{
    "name":"Budapest",
    "coords":"47.497912,19.040235",
    "interestingAt": "2019-01-01T05:00:00",
    "tags": "capital,favourite"
}

### Validation error
POST http://localhost:8080/api/locations
Accept: application/json
Content-Type: application/json

{
  "name":"",
  "coords":"47.497912,19.040235",
  "interestingAt": "2019-01-01T05:00:00",
  "tags": "capital,favourite"
}

### Modify location
POST http://localhost:8080/api/locations/1
Content-Type: application/json

{
  "id": 1,
  "name": "Budapest",
  "coords":"47.497912,19.040235",
  "interestingAt": "2022-12-31T23:59:59",
  "tags": "capital,favourite"
}

### Delete location
DELETE http://localhost:8080/api/locations/6
