version: '3'

services:
  locations-mariadb:
    image: mariadb
    restart: always
    ports:
      - '3306:3306'
    environment:
      MARIADB_DATABASE: locations
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 'yes' # aposztrófok nélkül boolean true-ként értelmezi
      MARIADB_USER: locations
      MARIADB_PASSWORD: locations

  locations-app:
    image: training360/locations
    ports:
      - '8080:8080'
    restart: always
    depends_on:
      - locations-mariadb
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:mariadb://locations-mariadb:3306/locations'
    entrypoint: ["./wait-for-it.sh", "-t", "120", "locations-mariadb:3306", "--", "java", "org.springframework.boot.loader.JarLauncher"]
